# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Toonstreet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Toonstreet

pod 'IQKeyboardManagerSwift'
pod 'SVProgressHUD'
pod 'TTTAttributedLabel'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Auth'
pod 'PureLayout','3.1.4'
#pod 'ScrollableSegmentedControl', '~> 1.5.0'

end
